version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /container/hovesa/data/nginx/certs:/etc/nginx/certs
    restart: always
    networks:
      - default
networks:
  default:
    driver: bridge
